import os

TELEGRAM_BOT_TOKEN = os.getenv("TELEGRAM_BOT_TOKEN", "8581514971:AAFUWd-VZ9wd7VfLiAU9gzqJL7CYv4GWzBE")
TELEGRAM_PROVIDER = os.getenv("TELEGRAM_PROVIDER", "REAL") # Default provider "MOCK" or "REAL"
TELEGRAM_CHAT_ID_TERRORISTS = os.getenv("TELEGRAM_CHAT_ID_TERRORISTS", "-5049988161")
TELEGRAM_CHAT_ID_COUNTERTERRORISTS = os.getenv("TELEGRAM_CHAT_ID_COUNTERTERRORISTS", "-5188192797")