import os

TELEGRAM_BOT_TOKEN = os.getenv("TELEGRAM_BOT_TOKEN", "")
TELEGRAM_PROVIDER = os.getenv("TELEGRAM_PROVIDER", "MOCK") # Default provider "MOCK" or "REAL"
TELEGRAM_CHAT_ID_TERRORISTS = os.getenv("TELEGRAM_CHAT_ID_TERRORISTS", "")
TELEGRAM_CHAT_ID_COUNTERTERRORISTS = os.getenv("TELEGRAM_CHAT_ID_COUNTERTERRORISTS", "")